version: '3'
services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: product-api-dynamodb-local
    command: -jar DynamoDBLocal.jar -dbPath /data -sharedDb
    volumes:
      - ./docker/dynamodb/data:/data
    ports:
      - 8435:8000