name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: |
          pip install -r requirements/dev.txt
      - uses: rrainn/dynamodb-action@v2.0.0
        with:
          port: 8435
          cors: "*"
      - run: |
          flake8
      - run: |
          pytest -s
        env:
          PYTHONPATH: ./
          AWS_ACCESS_KEY_ID: hoge
          AWS_SECRET_ACCESS_KEY: hoge
          AWS_DEFAULT_REGION: ap-northeast-1
      - uses: actions/upload-artifact@v2
        with:
          name: code-coverage-report
          path: reports

